# Generated by Django 3.0.2 on 2020-02-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20200211_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=120)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockIn_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sum_qty', models.FloatField(max_length=11)),
                ('stock_sum_buying_price', models.FloatField(max_length=120)),
                ('stock_sum_selling_price', models.FloatField(max_length=120)),
                ('stock_sum_status', models.CharField(default='in stock', max_length=120)),
                ('stock_sum_selling_type', models.CharField(max_length=120)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Barcode')),
            ],
        ),
        migrations.CreateModel(
            name='Product_StockIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_stock_no', models.CharField(max_length=100)),
                ('prod_stock_qty', models.FloatField(max_length=11)),
                ('prod_stock_type', models.CharField(max_length=120)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Barcode')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_subname', models.CharField(max_length=120)),
                ('product_description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='barcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
